/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as AdminInventarioRouteImport } from './routes/admin.inventario'
import { Route as SiteContactoemailRouteImport } from './routes/_site.contactoemail'
import { Route as SiteConfirmacionRouteImport } from './routes/_site.confirmacion'
import { Route as SiteCheckoutRouteImport } from './routes/_site.checkout'
import { Route as SiteCatalogoRouteImport } from './routes/_site.catalogo'
import { Route as SiteCarritoRouteImport } from './routes/_site.carrito'
import { Route as SiteProductoSlugRouteImport } from './routes/_site.producto.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventarioRoute = AdminInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AdminRoute,
} as any)
const SiteContactoemailRoute = SiteContactoemailRouteImport.update({
  id: '/contactoemail',
  path: '/contactoemail',
  getParentRoute: () => SiteRoute,
} as any)
const SiteConfirmacionRoute = SiteConfirmacionRouteImport.update({
  id: '/confirmacion',
  path: '/confirmacion',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutRoute = SiteCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCatalogoRoute = SiteCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCarritoRoute = SiteCarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductoSlugRoute = SiteProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrito': typeof SiteCarritoRoute
  '/catalogo': typeof SiteCatalogoRoute
  '/checkout': typeof SiteCheckoutRoute
  '/confirmacion': typeof SiteConfirmacionRoute
  '/contactoemail': typeof SiteContactoemailRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/productos': typeof AdminProductosRoute
  '/api/contact': typeof ApiContactRoute
  '/admin/': typeof AdminIndexRoute
  '/producto/$slug': typeof SiteProductoSlugRoute
}
export interface FileRoutesByTo {
  '/carrito': typeof SiteCarritoRoute
  '/catalogo': typeof SiteCatalogoRoute
  '/checkout': typeof SiteCheckoutRoute
  '/confirmacion': typeof SiteConfirmacionRoute
  '/contactoemail': typeof SiteContactoemailRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/productos': typeof AdminProductosRoute
  '/api/contact': typeof ApiContactRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/producto/$slug': typeof SiteProductoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_site/carrito': typeof SiteCarritoRoute
  '/_site/catalogo': typeof SiteCatalogoRoute
  '/_site/checkout': typeof SiteCheckoutRoute
  '/_site/confirmacion': typeof SiteConfirmacionRoute
  '/_site/contactoemail': typeof SiteContactoemailRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/productos': typeof AdminProductosRoute
  '/api/contact': typeof ApiContactRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/producto/$slug': typeof SiteProductoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/confirmacion'
    | '/contactoemail'
    | '/admin/inventario'
    | '/admin/productos'
    | '/api/contact'
    | '/admin/'
    | '/producto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/carrito'
    | '/catalogo'
    | '/checkout'
    | '/confirmacion'
    | '/contactoemail'
    | '/admin/inventario'
    | '/admin/productos'
    | '/api/contact'
    | '/'
    | '/admin'
    | '/producto/$slug'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/_site/carrito'
    | '/_site/catalogo'
    | '/_site/checkout'
    | '/_site/confirmacion'
    | '/_site/contactoemail'
    | '/admin/inventario'
    | '/admin/productos'
    | '/api/contact'
    | '/_site/'
    | '/admin/'
    | '/_site/producto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApiContactRoute: typeof ApiContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventario': {
      id: '/admin/inventario'
      path: '/inventario'
      fullPath: '/admin/inventario'
      preLoaderRoute: typeof AdminInventarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/contactoemail': {
      id: '/_site/contactoemail'
      path: '/contactoemail'
      fullPath: '/contactoemail'
      preLoaderRoute: typeof SiteContactoemailRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/confirmacion': {
      id: '/_site/confirmacion'
      path: '/confirmacion'
      fullPath: '/confirmacion'
      preLoaderRoute: typeof SiteConfirmacionRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout': {
      id: '/_site/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof SiteCheckoutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/catalogo': {
      id: '/_site/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof SiteCatalogoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/carrito': {
      id: '/_site/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof SiteCarritoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/producto/$slug': {
      id: '/_site/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof SiteProductoSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteCarritoRoute: typeof SiteCarritoRoute
  SiteCatalogoRoute: typeof SiteCatalogoRoute
  SiteCheckoutRoute: typeof SiteCheckoutRoute
  SiteConfirmacionRoute: typeof SiteConfirmacionRoute
  SiteContactoemailRoute: typeof SiteContactoemailRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteProductoSlugRoute: typeof SiteProductoSlugRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteCarritoRoute: SiteCarritoRoute,
  SiteCatalogoRoute: SiteCatalogoRoute,
  SiteCheckoutRoute: SiteCheckoutRoute,
  SiteConfirmacionRoute: SiteConfirmacionRoute,
  SiteContactoemailRoute: SiteContactoemailRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteProductoSlugRoute: SiteProductoSlugRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminInventarioRoute: typeof AdminInventarioRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInventarioRoute: AdminInventarioRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApiContactRoute: ApiContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
